import Papa from "papaparse";
import type { Vacancy } from "@/db/schema";

export const EXPORT_COLUMNS = [
  "id",
  "employer",
  "title",
  "url",
  "source",
  "source_verified",
  "found_on",
  "assessed_on",
  "layer",
  "location",
  "company_summary",
  "commute_minutes",
  "hours",
  "contract_type",
  "office_days",
  "remote_note",
  "salary",
  "language_requirement",
  "verdict",
  "verdict_reason",
  "fits",
  "fits_not",
  "doubts",
  "status",
  "status_note",
  "applied_on",
  "closed_on",
  "feedback_correct",
  "feedback_missed",
  "feedback_insight",
  "analysis",
  "cv_resume_id",
  "cv_url",
  "cv_linked_at",
  "vacancy_text",
  "created_at",
  "updated_at",
] as const;

export function vacanciesToCsv(rows: Vacancy[]): string {
  const data = rows.map((v) => ({
    id: v.id,
    employer: v.employer,
    title: v.title,
    url: v.url ?? "",
    source: v.source ?? "",
    source_verified: v.sourceVerified ? "true" : "false",
    found_on: v.foundOn ?? "",
    assessed_on: v.assessedOn ?? "",
    layer: v.layer,
    location: v.location ?? "",
    company_summary: v.companySummary ?? "",
    commute_minutes: v.commuteMinutes ?? "",
    hours: v.hours ?? "",
    contract_type: v.contractType,
    office_days: v.officeDays ?? "",
    remote_note: v.remoteNote ?? "",
    salary: v.salary ?? "",
    language_requirement: v.languageRequirement ?? "",
    verdict: v.verdict,
    verdict_reason: v.verdictReason ?? "",
    fits: v.fits ?? "",
    fits_not: v.fitsNot ?? "",
    doubts: v.doubts ?? "",
    status: v.status,
    status_note: v.statusNote ?? "",
    applied_on: v.appliedOn ?? "",
    closed_on: v.closedOn ?? "",
    feedback_correct: v.feedbackCorrect ?? "",
    feedback_missed: v.feedbackMissed ?? "",
    feedback_insight: v.feedbackInsight ?? "",
    analysis: v.analysis ? JSON.stringify(v.analysis) : "",
    cv_resume_id: v.cvResumeId ?? "",
    cv_url: v.cvUrl ?? "",
    cv_linked_at: v.cvLinkedAt ?? "",
    vacancy_text: v.vacancyText ?? "",
    created_at: v.createdAt,
    updated_at: v.updatedAt,
  }));
  // escapeFormulae: a vacancy text (or a title) can start with "=", "+", "-" or
  // "@"; a spreadsheet would run that as a formula when the export is opened.
  return Papa.unparse(data, { columns: [...EXPORT_COLUMNS], newline: "\n", escapeFormulae: true });
}
